[package]
name = "mobius"
version = "0.2.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono     = "0.4.19"
home       = "0.5.3"
structopt  = "0.3.22"
thiserror  = "1.0.28"
main_error = "0.1.1"